#!/usr/bin/env bash

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
ERROR-REDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "37i\ $REDIRECT" "/etc/nginx/sites-available/default"

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404error.html
sed -i "37i\ $ERROR-REDIRECT" /etc/nginx/sites-available/default

service nginx restart
